# Generated by Django 5.2.4 on 2025-08-22 11:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model3D',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('model_file', models.FileField(upload_to='models/3d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['glb', 'gltf', 'obj', 'fbx'])])),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='models/thumbnails/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_size', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
